languageCode = "pt-br"
title = "SalaDeMáquinas.TV"
baseurl = "http://salademaquinas.tv/"
theme = "darksimplicity"
min_version = 0.18
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true


[params]
description = "Suporte Digital, Redes e Dispositivos"
copyright = "&copy Copyright 2017. Matt Rhone and Dark Simplicity and sdmtv.net.br."
#google_analytics_id=""
#disqus_shortname=""


[taxonomies]
tag = "tags"

[menu]
  [[menu.top]]
  name = "Twitter"
  pre = ""
  weight = -100
  url = "http://www.twitter.com/saladmaquinastv"
  [[menu.top]]
  name = "RSS"
  pre = ""
  weight = -90
  url = "index.xml"
